// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtiqjemmqhpvtiiurwhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0aXFqZW1tcWhwdnRpaXVyd2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDAzNTAsImV4cCI6MjA2MDQ3NjM1MH0.F0bZNEUr4m2Vb5lImSQLWAcVpqQMsyntJ2aFmxNfP1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);